/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpacalculatorconsole;

import javax.swing.JOptionPane;

/**
 *
 * @author OrVee
 */
public class CGPACalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CGPACalculatorGUI
     */
    public CGPACalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sem1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        searchButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        searchButton3 = new javax.swing.JButton();
        sem2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        searchButton4 = new javax.swing.JButton();
        sem3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        searchButton5 = new javax.swing.JButton();
        sem4 = new javax.swing.JTextField();
        sem5 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        searchButton6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        searchButton7 = new javax.swing.JButton();
        sem6 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        searchButton8 = new javax.swing.JButton();
        sem7 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        searchButton9 = new javax.swing.JButton();
        sem8 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        getResult = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        searchButton10 = new javax.swing.JButton();
        resultField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        searchButton12 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CGPA Calculator | Diploma In Engineering");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 120, 215));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CGPA CALCULATOR  | PREPARE YOUR RESULT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jPanel4.setBackground(new java.awt.Color(0, 120, 215));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prepared By Java-8 | Sm's Solaiman");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 436, 680, 20));

        sem1.setBackground(new java.awt.Color(237, 237, 237));
        sem1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem1.setForeground(new java.awt.Color(255, 51, 51));
        sem1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem1.setBorder(null);
        jPanel1.add(sem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 30));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        searchButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton2.setForeground(new java.awt.Color(255, 255, 255));
        searchButton2.setText("1st Semester");
        searchButton2.setBorderPainted(false);
        searchButton2.setContentAreaFilled(false);
        searchButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton2.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(searchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 30));

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));

        searchButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton3.setForeground(new java.awt.Color(255, 255, 255));
        searchButton3.setText("2nd Semester");
        searchButton3.setBorderPainted(false);
        searchButton3.setContentAreaFilled(false);
        searchButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton3.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(searchButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        sem2.setBackground(new java.awt.Color(237, 237, 237));
        sem2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem2.setForeground(new java.awt.Color(255, 102, 51));
        sem2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem2.setBorder(null);
        jPanel1.add(sem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 30));

        jPanel6.setBackground(new java.awt.Color(255, 0, 102));

        searchButton4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton4.setForeground(new java.awt.Color(255, 255, 255));
        searchButton4.setText("3rd Semester");
        searchButton4.setBorderPainted(false);
        searchButton4.setContentAreaFilled(false);
        searchButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton4.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(searchButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 30));

        sem3.setBackground(new java.awt.Color(237, 237, 237));
        sem3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem3.setForeground(new java.awt.Color(255, 0, 102));
        sem3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem3.setBorder(null);
        jPanel1.add(sem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 190, 30));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));

        searchButton5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton5.setForeground(new java.awt.Color(255, 255, 255));
        searchButton5.setText("4th Semester");
        searchButton5.setBorderPainted(false);
        searchButton5.setContentAreaFilled(false);
        searchButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton5.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(searchButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        sem4.setBackground(new java.awt.Color(237, 237, 237));
        sem4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem4.setForeground(new java.awt.Color(0, 204, 0));
        sem4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem4.setBorder(null);
        jPanel1.add(sem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 190, 30));

        sem5.setBackground(new java.awt.Color(237, 237, 237));
        sem5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem5.setForeground(new java.awt.Color(102, 0, 102));
        sem5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem5.setBorder(null);
        jPanel1.add(sem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 190, 30));

        jPanel8.setBackground(new java.awt.Color(102, 0, 102));

        searchButton6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton6.setForeground(new java.awt.Color(255, 255, 255));
        searchButton6.setText("5th Semester");
        searchButton6.setBorderPainted(false);
        searchButton6.setContentAreaFilled(false);
        searchButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton6.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(searchButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 153));

        searchButton7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton7.setForeground(new java.awt.Color(255, 255, 255));
        searchButton7.setText("6th Semester");
        searchButton7.setBorderPainted(false);
        searchButton7.setContentAreaFilled(false);
        searchButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton7.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(searchButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        sem6.setBackground(new java.awt.Color(237, 237, 237));
        sem6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem6.setForeground(new java.awt.Color(0, 0, 153));
        sem6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem6.setBorder(null);
        jPanel1.add(sem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 190, 30));

        jPanel10.setBackground(new java.awt.Color(153, 0, 51));

        searchButton8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton8.setForeground(new java.awt.Color(255, 255, 255));
        searchButton8.setText("7th Semester");
        searchButton8.setBorderPainted(false);
        searchButton8.setContentAreaFilled(false);
        searchButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton8.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(searchButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 30));

        sem7.setBackground(new java.awt.Color(237, 237, 237));
        sem7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem7.setForeground(new java.awt.Color(153, 0, 51));
        sem7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem7.setBorder(null);
        jPanel1.add(sem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 190, 30));

        jPanel11.setBackground(new java.awt.Color(102, 0, 102));

        searchButton9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton9.setForeground(new java.awt.Color(255, 255, 255));
        searchButton9.setText("8th Semester");
        searchButton9.setBorderPainted(false);
        searchButton9.setContentAreaFilled(false);
        searchButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton9.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(searchButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 120, 30));

        sem8.setBackground(new java.awt.Color(237, 237, 237));
        sem8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sem8.setForeground(new java.awt.Color(102, 0, 102));
        sem8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sem8.setBorder(null);
        jPanel1.add(sem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 190, 30));

        jPanel13.setBackground(new java.awt.Color(0, 120, 215));

        getResult.setForeground(new java.awt.Color(255, 255, 255));
        getResult.setText("GET RESULT");
        getResult.setBorderPainted(false);
        getResult.setContentAreaFilled(false);
        getResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getResult.setPreferredSize(new java.awt.Dimension(36, 36));
        getResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getResult, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(getResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 500, 30));

        jTextField17.setBackground(new java.awt.Color(237, 237, 237));
        jTextField17.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 190, 30));

        jPanel12.setBackground(new java.awt.Color(204, 0, 204));

        searchButton10.setForeground(new java.awt.Color(255, 255, 255));
        searchButton10.setText("5th Semester");
        searchButton10.setBorderPainted(false);
        searchButton10.setContentAreaFilled(false);
        searchButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton10.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(searchButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 30));

        resultField.setBackground(new java.awt.Color(237, 237, 237));
        resultField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resultField.setForeground(new java.awt.Color(204, 0, 204));
        resultField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        jPanel1.add(resultField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 320, 30));

        jPanel14.setBackground(new java.awt.Color(204, 0, 204));

        searchButton12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchButton12.setForeground(new java.awt.Color(255, 255, 255));
        searchButton12.setText("YOUR FINAL CGPA IS:");
        searchButton12.setBorderPainted(false);
        searchButton12.setContentAreaFilled(false);
        searchButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton12.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 320, 30));

        jPanel15.setBackground(new java.awt.Color(255, 0, 0));

        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.setPreferredSize(new java.awt.Dimension(36, 36));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(696, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResultActionPerformed
        // TODO add your handling code here:
        try
        {
            double semester1 = Double.parseDouble(sem1.getText());
            double semester2 = Double.parseDouble(sem2.getText());
            double semester3 = Double.parseDouble(sem3.getText());
            double semester4 = Double.parseDouble(sem4.getText());
            double semester5 = Double.parseDouble(sem5.getText());
            double semester6 = Double.parseDouble(sem6.getText());
            double semester7 = Double.parseDouble(sem7.getText());
            double semester8 = Double.parseDouble(sem8.getText());
            
            double finalResult = (((semester1*5)/100)+((semester2*5)/100)+((semester3*5)/100)+((semester4*10)/100)+((semester5*15)/100)+((semester6*20)/100)+((semester7*25)/100)+((semester8*15)/100));
            String FinalResult = String.format("%.2f", finalResult);
            resultField.setText(FinalResult);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_getResultActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        sem1.setText(null);
        sem2.setText(null);
        sem3.setText(null);
        sem4.setText(null);
        sem5.setText(null);
        sem6.setText(null);
        sem7.setText(null);
        sem8.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton getResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField resultField;
    private javax.swing.JButton searchButton10;
    private javax.swing.JButton searchButton12;
    private javax.swing.JButton searchButton2;
    private javax.swing.JButton searchButton3;
    private javax.swing.JButton searchButton4;
    private javax.swing.JButton searchButton5;
    private javax.swing.JButton searchButton6;
    private javax.swing.JButton searchButton7;
    private javax.swing.JButton searchButton8;
    private javax.swing.JButton searchButton9;
    private javax.swing.JTextField sem1;
    private javax.swing.JTextField sem2;
    private javax.swing.JTextField sem3;
    private javax.swing.JTextField sem4;
    private javax.swing.JTextField sem5;
    private javax.swing.JTextField sem6;
    private javax.swing.JTextField sem7;
    private javax.swing.JTextField sem8;
    // End of variables declaration//GEN-END:variables
}
